### ISSUE TITLE
Missing cloudwatch data in Grafana

### ISSUE THREAD

**Issue by leemarosi36** [monitoringartist/grafana-aws-cloudwatch-dashboards#123] opened 2023-05-09 19:20 UTC
Hello Team,

I’m trying to find out Grafana using CloudWatch as datasource, It incorporate AWS metric with grafana application to plot the graphs. I have multiple aws account, but only few account shows data and for remaining aws account it shows no data.There are no error logs in log files regarding this.

I checked all the CloudWatch data and it’s coming fine on AWS console, but strangely missing in Grafana Interface.

Could you please help to understand what’s wrong here?
Would appreciate your support on this.

**Comment by jangaraj** [comment] 2023-05-09 20:15
This looks like a request for a support not an issue of the dashboard. Unfortunately, it is out of scope for this project. 
It looks like you did crossposting - https://community.grafana.com/t/no-data-in-grafana-cloudwatch-data-missing/87351 please solve it there.
Advice: always provide reproducible example

**Closed as completed by jangaraj** 2023-05-09 20:15 UTC
